#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'movieobjects'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
    movieobjects_vpc = vpc_parser.parse_vpcs( bld.env, ['movieobjects.vpc'], '..' )
    source = movieobjects_vpc["sources"]	
    includes = movieobjects_vpc["includes"]
    includes += [
       '../public',
       '../public/tier0',
       '../public/tier1',
       '../public/tier2',
       '../public/tier3',
    ]
    
    defines = movieobjects_vpc["defines"]

    libs = ['tier0','tier1','tier2','tier3']
    
    if bld.env.DEST_OS == 'android':
        libs += ['ANDROID_SUPPORT']
 
    install_path = bld.env.LIBDIR
    
    bld.stlib(
    	source   = source,
    	target   = PROJECT_NAME,
    	name     = PROJECT_NAME,
    	features = 'c cxx',
    	includes = includes,
    	defines  = defines,
    	use      = libs,
    	install_path = install_path,
    	subsystem = bld.env.MSVC_SUBSYSTEM,
    	idx      = bld.get_taskgen_count()
    )
